### ISSUE TITLE
has_validation macro requires validates_length_of to have a :within option specified

### ISSUE THREAD

**Issue by brandonweiss** [thumblemonks/riot-mongoid#1]
Right now the way the has_validation macro is written it requires a :within option to be specified, but that isn't necessarily always the case. For instance someone might just want to validate the length of something with a :minimum of 1.

**Comment by brandonweiss** [comment]
I should have said, it's a relatively simple fix so I assumed you'd want to just do it yourself, but if you want I can fork it, make the change and send a pull request. Up to you.

**Comment by achiurizo** [comment]
hey, thanks for the catch, i've submit a fix here: cc33083ce7cb4af28b5a7562071e9500d0a7805b

ill probably release a new version once i get around to adding some additional features as well. reopen if this issue still persists. thanks!

**Comment by brandonweiss** [comment]
Yep, that fixed it, thanks!
